### ISSUE TITLE
Tinymist preview feature not yet released

### ISSUE THREAD

**Issue by asmund20** [chomosuke/typst-preview.nvim#47]
# Please release the tinymist preview feature!
The tinymist binary has some useful features, for example the preview feature added to the docs in #46. 

The feature is committed to the master branch (and therefore I assume that it works). There is, however not a release including this feature yet. That is confusing, as it is added to both the readme and docs and does not work (results in unexpexted  arguments because it does not call tinymist preview ..args but just tinymist ..args without the support added in #43.

**Comment by asmund20** [comment]
I recommend removing the tag=0.3.* from the install to use the newly committed features even though they are not released yet.

**Comment by max397574** [comment]
every user can just remove that themselves in their config

**Comment by chomosuke** [comment]
Hey sorry, I did not realize I was so far behind in my release! I think everytime I merge a PR I tell myself I'll release it later but I never do, I will start improving in this from now on. 

And sorry for the late reply, I've been finding myself in lack of motivation to maintain this plugin this year since I dropped out of my research and am no longer using typst. There's quite a lot of to-do for this plugin that I need to attend to.

**Comment by max397574** [comment]
@chomosuke
1. you could use release please
2. Would you mind me rewriting this plugin as a new plugin? I thought about this anyway but since you're not rly maintaining it anymore that's even more reason todo so

**Comment by chomosuke** [comment]
@max397574 
1. I have just released. 
2. Would you like to become the maintainer of this plugin instead? If you do use typst on a daily basis you'll probably do a better job than me. You can also rewrite the plugin however you like.

**Comment by max397574** [comment]
I use typst for multiple hours every day so I make really heavy use of this plugin. I'll take a look at the codebase first before I decide what to do

**Comment by max397574** [comment]
@chomosuke would you be okay with me adding this to a plugin I'm working on: typst-tools.nvim?
also has various utils some lsp,treesitter stuff, snippets etc

I'd copy over most of the code and ofc course give credits to you in the readme

**Comment by chomosuke** [comment]
Hi @max397574, would you like to add this plugin as a dependency instead? That way people who only want the preview can still get only the preview.

**Comment by max397574** [comment]
if I'd copy over the things this plugin would still exist for people who only want preview

**Comment by chomosuke** [comment]
Oh yes indeed, that make sense. Yes I don't mind feel free.

**Comment by chomosuke** [comment]
I wonder if this plugin will still be necessary once typst-tools is completed. I also don't think that many people would want to use preview only without the language server. On a second thought, something like typst-tools.nvim really make much more sense now that tinymist exist. I will consider sunsetting typst-preview.nvim just like Enter-tainer has done to typst-preview.
